#!/usr/bin/env python3
"""Run a small OpenClaw-facing embedded trace batch.

This helper is provided for reproducibility of the interface-validation traces.
It assumes it is launched from the package root:

    python3 openclaw_interface/scripts/run_agenttrace_dep20_batch.py

The quantitative tables in the manuscript are generated by the controlled
sandbox artifacts under artifacts/reported_results; this script demonstrates how
the same OpenClaw-facing reset/finalize interface was exercised for embedded
agent trace validation.
"""
from pathlib import Path
import subprocess

root = Path(__file__).resolve().parents[2]
code_dir = root / "code"
out_dir = root / "openclaw_interface" / "generated_trace_outputs"
runlist = out_dir / "agenttrace_dep20_runlist.csv"
summary = out_dir / "agenttrace_dep20_summary.csv"
out_dir.mkdir(parents=True, exist_ok=True)

seeds = ["20", "21", "23", "30", "34", "36", "58", "62", "68", "69"]
subprocess.run([
    "python3", str(code_dir / "make_matched_budget_runlist.py"),
    "--slices", "dependency_sensitive",
    "--seeds", *seeds,
    "--policies", "uncertainty_only_matched_budget", "harm_aware_selective",
    "--out", str(runlist),
    "--prefix", "agenttrace",
], check=True)

subprocess.run([
    "python3", str(code_dir / "run_runlist.py"),
    "--runlist", str(runlist),
    "--summary-csv", str(summary),
    "--uncertainty-threshold", "0.422000",
    "--harm-threshold", "0.291537",
    "--random-verify-prob", "0.500000",
    "--skip-done",
], check=True)

print("AGENTTRACE_BATCH_DONE")
print("runlist:", runlist)
print("summary:", summary)
